"""

Resolved v35 curriculum defaults.

It is the editable, top-level contract used by the internal phased curriculum
builder before phase-specific overrides are applied.  The values were materialized from
``teacher_dagger_upstream_fasttd3_v35_6cm_xyz_align_stage`` so later curriculum
work does not depend on hidden profile inheritance.

File map:

V35_MODULE:             Define v35 module constant
V35_SCRIPT:             Define v35 script constant
V35_BASE_ARGS:          Define v35 base args constant
V35_BASE_ENV:           Define v35 base env constant
_remove_arg:            Handle remove arg logic
_replace_arg:           Handle replace arg logic
_set_flag:              Handle set flag logic
_force_v35_entrypoint:  Ensure flattened v35 plans launch the native training module
apply_v35_base:         Apply the full flattened v35 contract to a mutable command/env plan
"""

from __future__ import annotations

from typing import Any

V35_MODULE = 'training.native_entrypoint'
V35_SCRIPT = ''

V35_BASE_ARGS: dict[str, str | bool] = {'--actor-bc-action-gate-mode': 'raw',
 '--actor-lr'                                             : '0.0003',
 '--actor-pre-tanh-l2'                                    : '0.0',
 '--actor-q-action-gate-mode'                             : 'raw',
 '--arm-action-scale-profile'                             : 'topdown',
 '--arm-controller'                                       : 'policy',
 '--assist-noise-arm'                                     : '0.00',
 '--assist-noise-clean-bc-target'                         : '1',
 '--assist-noise-finger'                                  : '0.000',
 '--batch-size'                                           : '384',
 '--bc-only-arm-weight'                                   : '4.0',
 '--bc-only-finger-weight'                                : '2.0',
 '--bc-only-steps'                                        : '200000',
 '--bc-only-weight'                                       : '10.0',
 '--checkpoint-every'                                     : '50000',
 '--checkpoint-path'                                      : 'runs/teacher_dagger_upstream_fasttd3_v35_6cm_xyz_align_stage/latest.pt',
 '--contact-finger-close-cap'                             : '0.92',
 '--contact-preroll-ik-descend-z'                         : '0.06',
 '--contact-preroll-touch-mode'                           : 'off',
 '--contact-start-mode'                                   : 'reset',
 '--contact-teacher-hold-fraction-cap'                    : '0.15',
 '--critic-grad-clip'                                     : '5.0',
 '--critic-lr'                                            : '0.0001',
 '--device'                                               : 'cuda:0',
 '--disable-camera-perception'                            : True,
 '--eval-every'                                           : '500000',
 '--eval-episodes'                                        : '0',
 '--eval-steps'                                           : '1000',
 '--exploration-noise'                                    : '0.01',
 '--exploration-noise-finger'                             : '0.012',
 '--fasttd3-actor-hidden-dim'                             : '512',
 '--fasttd3-critic-hidden-dim'                            : '1024',
 '--fasttd3-init-scale'                                   : '0.01',
 '--fasttd3-num-atoms'                                    : '51',
 '--fasttd3-std-max'                                      : '0.4',
 '--fasttd3-std-min'                                      : '0.001',
 '--fasttd3-use-cdq'                                      : '1',
 '--fasttd3-v-max'                                        : '0.0',
 '--fasttd3-v-min'                                        : '-5.0',
 '--fasttd3-weight-decay'                                 : '0.0',
 '--finger-action-mode'                                   : 'absolute',
 '--finger-delta-scale'                                   : '0.05',
 '--gamma'                                                : '0.995',
 '--handoff-checkpoint-path'                              : 'runs/replay_handoffs/teacher_dagger_upstream_fasttd3_v35_6cm_xyz_align_stage/handoff_replay.pt',
 '--headless'                                             : True,
 '--include-wrist-roll'                                   : True,
 '--log-every'                                            : '2500',
 '--log-jsonl'                                            : 'runs/teacher_dagger_upstream_fasttd3_v35_6cm_xyz_align_stage/log.jsonl',
 '--n-step'                                               : '1',
 '--native-contact-attr-parts'                            : True,
 '--native-teacher-provider'                              : 'env',
 '--noise-clip'                                           : '0.05',
 '--num-envs'                                             : '100',
 '--observation-normalization'                            : True,
 '--policy-assist-decay-start-steps'                      : '-1',
 '--policy-assist-decay-steps'                            : '600000',
 '--policy-assist-mix'                                    : '1.0',
 '--policy-assist-mix-floor'                              : '0.25',
 '--policy-bc-relabel'                                    : '1',
 '--policy-delay'                                         : '1',
 '--policy-noise'                                         : '0.0',
 '--policy-noise-finger'                                  : '0.0',
 '--privileged-critic'                                    : True,
 '--replay-size'                                          : '1000000',
 '--rl-actor-freeze-steps'                                : '50000',
 '--rl-actor-lr'                                          : '8e-06',
 '--rl-actor-pre-tanh-l2'                                 : '-1.0',
 '--rl-critic-grad-clip'                                  : '-1.0',
 '--rl-critic-lr'                                         : '5e-05',
 '--rl-exploration-noise'                                 : '0.0',
 '--rl-exploration-noise-finger'                          : '0.02',
 '--rl-gamma'                                             : '-1.0',
 '--rl-n-step'                                            : '3',
 '--rl-noise-clip'                                        : '0.05',
 '--rl-phase-start-steps'                                 : '200000',
 '--rl-policy-assist-decay-start-steps'                   : '-1',
 '--rl-policy-assist-decay-steps'                         : '750000',
 '--rl-policy-assist-mix'                                 : '1.0',
 '--rl-policy-assist-mix-floor'                           : '0.65',
 '--rl-policy-bc-relabel'                                 : '1',
 '--rl-policy-delay'                                      : '4',
 '--rl-policy-noise'                                      : '0.0',
 '--rl-policy-noise-finger'                               : '0.02',
 '--rl-reset-critic-optimizers-on-switch'                 : '1',
 '--rl-sync-targets-on-switch'                            : '1',
 '--rl-target-q-clip'                                     : '50',
 '--rl-tau'                                               : '0.0005',
 '--rl-teacher-bc-arm-weight'                             : '10.0',
 '--rl-teacher-bc-decay-steps'                            : '1000000',
 '--rl-teacher-bc-finger-weight'                          : '4.0',
 '--rl-teacher-bc-weight'                                 : '0.0',
 '--rl-updates-per-step'                                  : '8',
 '--rolling-checkpoint-every'                             : '50000',
 '--rolling-checkpoint-keep'                              : '16',
 '--seed'                                                 : '7',
 '--sleep'                                                : '0.0',
 '--start-steps'                                          : '50000',
 '--target-q-clip'                                        : '50',
 '--task'                                                 : 'Isaac-Topdown-Curriculum-G129-Dex3-Joint',
 '--tau'                                                  : '0.005',
 '--td3-backend'                                          : 'upstream_fasttd3',
 '--teacher-arm-source'                                   : 'ik',
 '--teacher-bc-arm-weight'                                : '10.0',
 '--teacher-bc-decay-steps'                               : '600000',
 '--teacher-bc-finger-weight'                             : '4.0',
 '--teacher-bc-weight'                                    : '0.0',
 '--teacher-lift-ramp-steps'                              : '60',
 '--teacher-lift-z'                                       : '0.05',
 '--topdown-contact-teacher'                              : True,
 '--topdown-contact-teacher-close-rate'                   : '0.006',
 '--topdown-contact-teacher-descent-z'                    : '0.08',
 '--topdown-contact-teacher-inward-m'                     : '0.0',
 '--topdown-contact-teacher-max-fraction'                 : '0.78',
 '--topdown-contact-teacher-middle-scale'                 : '0.0',
 '--topdown-contact-teacher-missing-contact-extra-descent': '0.005',
 '--topdown-contact-teacher-missing-contact-extra-inward' : '0.0',
 '--topdown-contact-teacher-start-fraction'               : '0.2',
 '--topdown-mirror-middle-to-index'                       : True,
 '--topdown-preroll-fraction'                             : '0.0',
 '--topdown-preroll-max-steps'                            : '250',
 '--topdown-preroll-unlock-progress'                      : '0.0',
 '--total-steps'                                          : '700000',
 '--updates-per-step'                                     : '12'
 }

V35_BASE_ENV: dict[str, str] = {'ACTOR_BC_ACTION_GATE_MODE': 'raw',
 'ACTOR_FREEZE_STEPS'                                        : '0',
 'ACTOR_LR'                                                  : '0.0003',
 'ACTOR_PRE_TANH_L2'                                         : '0.0',
 'ACTOR_Q_ACTION_GATE_MODE'                                  : 'raw',
 'ALLOW_HANDOFF_SOURCE_HASH_MISMATCH'                        : '0',
 'ALLOW_WARMSTART'                                           : '0',
 'ARM_ACTION_SCALE_PROFILE'                                  : 'topdown',
 'ARM_CONTROLLER'                                            : 'policy',
 'ASSIST_NOISE_ARM'                                          : '0.01',
 'ASSIST_NOISE_CLEAN_BC_TARGET'                              : '1',
 'ASSIST_NOISE_FINGER'                                       : '0.004',
 'BATCH_SIZE'                                                : '384',
 'BC_ONLY_ARM_WEIGHT'                                        : '4.0',
 'BC_ONLY_FINGER_WEIGHT'                                     : '2.0',
 'BC_ONLY_STEPS'                                             : '200000',
 'BC_ONLY_WEIGHT'                                            : '10.0',
 'BC_TARGET_INCLUDES_INPOCKET_ARM_HOLD'                      : '0',
 'CHECKPOINT_EVERY'                                          : '50000',
 'CHECKPOINT_PATH'                                           : 'runs/teacher_dagger_upstream_fasttd3_v35_6cm_xyz_align_stage/latest.pt',
 'CONTACT_FINGER_CLOSE_CAP'                                  : '0.92',
 'CONTACT_PREROLL_IK_DESCEND_Z'                              : '0.06',
 'CONTACT_PREROLL_TOUCH_MODE'                                : 'off',
 'CONTACT_START_MODE'                                        : 'reset',
 'CONTACT_TEACHER_HOLD_FRACTION_CAP'                         : '0.15',
 'CRITIC_BURN_IN_STEPS'                                      : '0',
 'CRITIC_GRAD_CLIP'                                          : '5.0',
 'CRITIC_LR'                                                 : '0.0001',
 'CUBLAS_WORKSPACE_CONFIG'                                   : ':4096:8',
 'CURRICULUM_ALIGN_HOLD_STEPS'                               : '5',
 'CURRICULUM_BACK_FINGER_SPREAD_OFFSET'                      : '0.02',
 'CURRICULUM_BLOCK_DRIFT_THRESHOLD'                          : '0.5',
 'CURRICULUM_BLOCK_XY_VEL_SOFT_CAP'                          : '0.5',
 'CURRICULUM_CONTACT_BLOCK_DISP_MAX'                         : '0.06',
 'CURRICULUM_CONTACT_FINGER_CENTER_ERR_NORM_CAP'             : '3.0',
 'CURRICULUM_CONTACT_FINGER_CENTER_ERR_SCALE'                : '0.035',
 'CURRICULUM_CONTACT_POSE_HOLD_STEPS'                        : '4',
 'CURRICULUM_CONTACT_POSE_READY_FALLBACK_ALIGN_ERR_MAX'      : '999.0',
 'CURRICULUM_CONTACT_POSE_READY_FALLBACK_OPPOSED_GATE_MIN'   : '-1.0',
 'CURRICULUM_CONTACT_POSE_READY_FALLBACK_PALM_DIST_MAX'      : '0.1',
 'CURRICULUM_CONTACT_POSE_READY_FALLBACK_PALM_HEIGHT_MAX'    : '0.09',
 'CURRICULUM_CONTACT_POSE_READY_FALLBACK_PALM_ORIENT_MAX_DEG': '180.0',
 'CURRICULUM_CONTACT_POSE_READY_FALLBACK_PALM_YAW_MAX_DEG'   : '180.0',
 'CURRICULUM_CONTACT_POSE_READY_FALLBACK_STEPS'              : '0',
 'CURRICULUM_FACE_HALF_EXTENT'                               : '0.0225',
 'CURRICULUM_FINGER_CENTER_ALIGN_ANGLE_MAX_DEG'              : '8.0',
 'CURRICULUM_FINGER_CENTER_ALIGN_ERR_MAX'                    : '0.0',
 'CURRICULUM_FINGER_CENTER_HOLD_STEPS'                       : '1',
 'CURRICULUM_FINGER_CENTER_LATCH'                            : '0',
 'CURRICULUM_FINGER_CENTER_MAX_TIP_XY_MAX'                   : '0.0',
 'CURRICULUM_FINGER_CENTER_REQUIRES_CONTACT_POSE'            : '0',
 'CURRICULUM_FINGER_CENTER_TIP_XY_MAX'                       : '0.0',
 'CURRICULUM_FINGER_CENTER_TIP_Z_MAX'                        : '0.0',
 'CURRICULUM_FINGER_CENTER_USE_XYZ_GATE'                     : '1',
 'CURRICULUM_FINGER_CENTER_XYZ_GATE_MIN'                     : '1e-06',
 'CURRICULUM_FINGER_FACE_TOP_MARGIN'                         : '0.009',
 'CURRICULUM_FINGER_UNLOCK_RAMP_STEPS'                       : '160',
 'CURRICULUM_FINGER_UNLOCK_REQUIRES_CENTER'                  : '0',
 'CURRICULUM_LIFT_HEIGHT_PROGRESS_REQUIRES_GRIP'             : '1',
 'CURRICULUM_LIFT_PENALTY_HEIGHT_RAMP'                       : '0.02',
 'CURRICULUM_LIFT_PENALTY_HEIGHT_START'                      : '0.02',
 'CURRICULUM_REACH_HOLD_STEPS'                               : '5',
 'CURRICULUM_STAGE1_ALIGN_ERR_MAX'                           : '999.0',
 'CURRICULUM_STAGE1_LINE_ANGLE_MAX_DEG'                      : '65',
 'CURRICULUM_STAGE1_NO_CONTACT_MAX'                          : '0.08',
 'CURRICULUM_STAGE1_OPPOSED_GATE_MIN'                        : '-1.0',
 'CURRICULUM_STAGE1_PALM_DIST_MAX'                           : '0.2',
 'CURRICULUM_STAGE1_PALM_HEIGHT_MAX'                         : '0.1',
 'CURRICULUM_STAGE1_PALM_ORIENT_MAX_DEG'                     : '180.0',
 'CURRICULUM_STAGE1_PALM_YAW_MAX_DEG'                        : '180.0',
 'CURRICULUM_STAGE2_ALIGN_ERR_MAX'                           : '999.0',
 'CURRICULUM_STAGE2_FINGER_XYZ_GATE_FULL_M'                  : '0.035',
 'CURRICULUM_STAGE2_FINGER_XYZ_GATE_START_M'                 : '0.075',
 'CURRICULUM_STAGE2_LINE_ANGLE_MAX_DEG'                      : '8.0',
 'CURRICULUM_STAGE2_NO_CONTACT_MAX'                          : '2.01',
 'CURRICULUM_STAGE2_OPPOSED_GATE_MIN'                        : '-1.0',
 'CURRICULUM_STAGE2_PALM_DIST_MAX'                           : '0.14',
 'CURRICULUM_STAGE2_PALM_HEIGHT_MAX'                         : '0.1',
 'CURRICULUM_STAGE2_PALM_ORIENT_MAX_DEG'                     : '180.0',
 'CURRICULUM_STAGE2_PALM_YAW_MAX_DEG'                        : '180.0',
 'CURRICULUM_SUCCESS_ALIGN_ERR_MAX'                          : '999.0',
 'CURRICULUM_SUCCESS_CENTER_ALIGN_ANGLE_MAX_DEG'             : '10',
 'CURRICULUM_SUCCESS_CENTER_HOLD_STEPS'                      : '2',
 'CURRICULUM_SUCCESS_CENTER_TIP_XY_MAX'                      : '0.018',
 'CURRICULUM_SUCCESS_CENTER_TIP_Z_MAX'                       : '0.045',
 'CURRICULUM_SUCCESS_OPPOSED_GATE_MIN'                       : '-1.0',
 'CURRICULUM_SUCCESS_PALM_ORIENT_MAX_DEG'                    : '180.0',
 'CURRICULUM_SUCCESS_PALM_YAW_MAX_DEG'                       : '180.0',
 'CURRICULUM_THREE_FINGER_CENTERING'                         : '0',
 'CURRICULUM_TOPDOWN_HOVER_ABOVE_BLOCK_TOP'                  : '0.075',
 'CURRICULUM_W_ALIGNMENT_DEGRADATION'                        : '-25.0',
 'CURRICULUM_W_ALIGN_ALIGNMENT_ERROR_QUADRATIC'              : '-6',
 'CURRICULUM_W_ALIGN_FINGERTIP_LINE_ANGLE_QUADRATIC'         : '-0.6',
 'CURRICULUM_W_BLOCK_ANGULAR_VELOCITY_PENALTY'               : '-1',
 'CURRICULUM_W_BLOCK_DROP_PENALTY'                           : '-5',
 'CURRICULUM_W_BLOCK_OFF_TABLE_BONUS'                        : '15',
 'CURRICULUM_W_BLOCK_TILT_LIFT_PENALTY'                      : '-15',
 'CURRICULUM_W_BLOCK_XY_VELOCITY_PENALTY'                    : '-2',
 'CURRICULUM_W_CENTERED_LIFT_PROGRESS'                       : '0',
 'CURRICULUM_W_CENTERED_UPRIGHT_LIFT_BONUS'                  : '20',
 'CURRICULUM_W_CONTACT_ALIGNMENT_ERROR'                      : '-2.0',
 'CURRICULUM_W_CONTACT_ALIGNMENT_ERROR_QUADRATIC'            : '-10.0',
 'CURRICULUM_W_CONTACT_BILATERAL_CONTACT'                    : '0',
 'CURRICULUM_W_CONTACT_BILATERAL_IMBALANCE'                  : '0',
 'CURRICULUM_W_CONTACT_CENTERED_CONTACT'                     : '6.0',
 'CURRICULUM_W_CONTACT_FINGER_CENTER_X_ERROR_QUADRATIC'      : '-1.0',
 'CURRICULUM_W_CONTACT_FINGER_CENTER_Y_ERROR_QUADRATIC'      : '-1.0',
 'CURRICULUM_W_CONTACT_LIFT_PROGRESS'                        : '0',
 'CURRICULUM_W_CONTACT_ONE_SIDED'                            : '-4',
 'CURRICULUM_W_CONTACT_ONE_SIDED_FLIP'                       : '0',
 'CURRICULUM_W_CONTACT_OPPOSED_CONTACT'                      : '12',
 'CURRICULUM_W_CONTACT_PREUNLOCK_NO_CONTACT'                 : '0',
 'CURRICULUM_W_CONTACT_PREUNLOCK_POCKET'                     : '0',
 'CURRICULUM_W_CONTACT_SUCCESS_NOW_CONTINUOUS'               : '0',
 'CURRICULUM_W_LIFT_HEIGHT_PROGRESS'                         : '2',
 'CURRICULUM_W_LIFT_WITH_GRIP'                               : '8',
 'CURRICULUM_W_LIFT_XY_DRIFT_PENALTY'                        : '-12',
 'CURRICULUM_W_REACH_ALIGNMENT_ERROR_QUADRATIC'              : '-6',
 'CURRICULUM_W_REACH_FINGERTIP_LINE_ANGLE_QUADRATIC'         : '-0.75',
 'CURRICULUM_W_STAGE2_FLOOR'                                 : '0.5',
 'CURRICULUM_W_STEP_COST'                                    : '-0.005',
 'CURRICULUM_W_UNCENTERED_LIFT_PENALTY'                      : '-8',
 'DAGGER_RESUME_POLICY_ASSIST_DECAY_STEPS'                   : '-1',
 'DAGGER_RESUME_POLICY_ASSIST_MIX'                           : '-1.0',
 'DAGGER_RESUME_POLICY_ASSIST_MIX_FLOOR'                     : '-1.0',
 'DEVICE'                                                    : 'cuda:0',
 'DISABLE_CAMERA_PERCEPTION'                                 : '1',
 'ENABLE_CAMERAS'                                            : '0',
 'ENPM690_CUDNN_BENCHMARK'                                   : '0',
 'ENPM690_CUDNN_DETERMINISTIC'                               : '1',
 'ENPM690_NUMPY_SEED'                                        : '1',
 'ENPM690_TORCH_DETERMINISTIC'                               : '1',
 'ENPM690_TORCH_DETERMINISTIC_WARN_ONLY'                     : '1',
 'EVAL_EPISODES'                                             : '2',
 'EVAL_STEPS'                                                : '600',
 'EXPLORATION_NOISE'                                         : '0.01',
 'EXPLORATION_NOISE_FINGER'                                  : '0.012',
 'FASTTD3_ACTOR_HIDDEN_DIM'                                  : '512',
 'FASTTD3_CRITIC_HIDDEN_DIM'                                 : '1024',
 'FASTTD3_INIT_SCALE'                                        : '0.01',
 'FASTTD3_NUM_ATOMS'                                         : '51',
 'FASTTD3_STD_MAX'                                           : '0.4',
 'FASTTD3_STD_MIN'                                           : '0.001',
 'FASTTD3_USE_CDQ'                                           : '1',
 'FASTTD3_V_MAX'                                             : '0.0',
 'FASTTD3_V_MIN'                                             : '-5.0',
 'FASTTD3_WEIGHT_DECAY'                                      : '0.0',
 'FINGER_ACTION_MODE'                                        : 'absolute',
 'FINGER_DELTA_SCALE'                                        : '0.05',
 'FINGER_UNLOCK_REQUIRES_ARM_HOLD'                           : '0',
 'FORCE_DAGGER_AFTER_RESUME'                                 : '0',
 'GAMMA'                                                     : '0.995',
 'HANDOFF_CHECKPOINT_PATH'                                   : 'runs/replay_handoffs/teacher_dagger_upstream_fasttd3_v35_6cm_xyz_align_stage/handoff_replay.pt',
 'HEADLESS'                                                  : '1',
 'INCLUDE_WAIST_YAW'                                         : '0',
 'INCLUDE_WRIST_ROLL'                                        : '1',
 'INPOCKET_ARM_HOLD'                                         : '0',
 'INPOCKET_ARM_HOLD_CENTER_ALIGN_ANGLE_MAX_DEG'              : '1.0',
 'INPOCKET_ARM_HOLD_CENTER_TIP_XY_MAX'                       : '0.03',
 'INPOCKET_ARM_HOLD_CENTER_TIP_Z_MAX'                        : '0.045',
 'INPOCKET_ARM_HOLD_FREEZE_REQUIRES_CONTACT_CENTER'          : '1',
 'INPOCKET_ARM_HOLD_FREEZE_REQUIRES_FINGER_CENTER'           : '0',
 'INPOCKET_LATCH_HOLD_STEPS'                                 : '3',
 'LOG_EVERY'                                                 : '2500',
 'NOISE_CLIP'                                                : '0.05',
 'NUM_ENVS'                                                  : '100',
 'N_STEP'                                                    : '1',
 'OBSERVATION_NORMALIZATION'                                 : '1',
 'PHASE1_TEACHER_ONLY'                                       : '0',
 'POLICY_ASSIST_DECAY_START_STEPS'                           : '-1',
 'POLICY_ASSIST_DECAY_STEPS'                                 : '600000',
 'POLICY_ASSIST_MIX'                                         : '1.0',
 'POLICY_ASSIST_MIX_FLOOR'                                   : '0.25',
 'POLICY_BC_RELABEL'                                         : '1',
 'POLICY_DELAY'                                              : '1',
 'POLICY_NOISE'                                              : '0.0',
 'POLICY_NOISE_FINGER'                                       : '0.0',
 'PRIVILEGED_CRITIC'                                         : '1',
 'PYTHONHASHSEED'                                            : '7',
 'REPLAY_SIZE'                                               : '1000000',
 'RESET_OBS_STATS_ON_RESUME'                                 : '1',
 'RESET_OPTIMIZERS_ON_RESUME'                                : '0',
 'RESUME_GLOBAL_STEP'                                        : '0',
 'RESUME_REPLAY'                                             : '0',
 'REWARD_NORMALIZATION'                                      : '0',
 'RL_ACTOR_FREEZE_STEPS'                                     : '50000',
 'RL_ACTOR_LR'                                               : '8e-06',
 'RL_ACTOR_PRE_TANH_L2'                                      : '-1.0',
 'RL_CRITIC_GRAD_CLIP'                                       : '-1.0',
 'RL_CRITIC_LR'                                              : '5e-05',
 'RL_EXPLORATION_NOISE'                                      : '0.0',
 'RL_EXPLORATION_NOISE_FINGER'                               : '0.02',
 'RL_GAMMA'                                                  : '-1.0',
 'RL_NOISE_CLIP'                                             : '0.05',
 'RL_N_STEP'                                                 : '1',
 'RL_PHASE_START_STEPS'                                      : '200000',
 'RL_POLICY_ASSIST_DECAY_START_STEPS'                        : '-1',
 'RL_POLICY_ASSIST_DECAY_STEPS'                              : '750000',
 'RL_POLICY_ASSIST_MIX'                                      : '1.0',
 'RL_POLICY_ASSIST_MIX_FLOOR'                                : '0.65',
 'RL_POLICY_BC_RELABEL'                                      : '1',
 'RL_POLICY_DELAY'                                           : '4',
 'RL_POLICY_NOISE'                                           : '0.0',
 'RL_POLICY_NOISE_FINGER'                                    : '0.02',
 'RL_RESET_CRITIC_OPTIMIZERS_ON_SWITCH'                      : '1',
 'RL_SYNC_TARGETS_ON_SWITCH'                                 : '1',
 'RL_TARGET_Q_CLIP'                                          : '50',
 'RL_TAU'                                                    : '0.0005',
 'RL_TEACHER_BC_ARM_WEIGHT'                                  : '4.0',
 'RL_TEACHER_BC_DECAY_STEPS'                                 : '1000000',
 'RL_TEACHER_BC_FINGER_WEIGHT'                               : '1.0',
 'RL_TEACHER_BC_WEIGHT'                                      : '0.0',
 'RL_UPDATES_PER_STEP'                                       : '8',
 'ROLLING_CHECKPOINT_EVERY'                                  : '50000',
 'ROLLING_CHECKPOINT_KEEP'                                   : '16',
 'RUN_DIR'                                                   : 'runs/teacher_dagger_upstream_fasttd3_v35_6cm_xyz_align_stage',
 'SAVE_REPLAY_IN_CHECKPOINT'                                 : '0',
 'SEED'                                                      : '7',
 'SLEEP'                                                     : '0.0',
 'SOFT_POLICY_ARM_ASSIST'                                    : '0',
 'START_STEPS'                                               : '50000',
 'STOP_AFTER_HANDOFF_CHECKPOINT'                             : '0',
 'TARGET_Q_CLIP'                                             : '50',
 'TASK'                                                      : 'Isaac-Topdown-Curriculum-G129-Dex3-Joint',
 'TAU'                                                       : '0.005',
 'TD3_BACKEND'                                               : 'upstream_fasttd3',
 'TEACHER_ARM_SOURCE'                                        : 'ik',
 'TEACHER_BC_ARM_WEIGHT'                                     : '3.0',
 'TEACHER_BC_DECAY_STEPS'                                    : '600000',
 'TEACHER_BC_FINGER_WEIGHT'                                  : '1.5',
 'TEACHER_BC_WEIGHT'                                         : '0.0',
 'TEACHER_LIFT_RAMP_STEPS'                                   : '60',
 'TEACHER_LIFT_Z'                                            : '0.07',
 'TEACHER_TOPDOWN_PALM_OFFSET_X'                             : '0.0',
 'TEACHER_TOPDOWN_PALM_OFFSET_Y'                             : '0.0',
 'TOPDOWN_BLOCK_DYNAMIC_FRICTION'                            : '1.0',
 'TOPDOWN_BLOCK_JITTER_X'                                    : '0.015',
 'TOPDOWN_BLOCK_JITTER_Y'                                    : '0.015',
 'TOPDOWN_BLOCK_MASS'                                        : '0.25',
 'TOPDOWN_BLOCK_SIZE'                                        : '0.06',
 'TOPDOWN_BLOCK_STATIC_FRICTION'                             : '1.2',
 'TOPDOWN_CONTACT_FORCE_SATURATION'                          : '1.5',
 'TOPDOWN_CONTACT_FORCE_THRESHOLD'                           : '0.05',
 'TOPDOWN_CONTACT_OFFSET'                                    : '0.002',
 'TOPDOWN_CONTACT_TEACHER'                                   : '1',
 'TOPDOWN_CONTACT_TEACHER_ARM_SERVO_USES_CONTACT_MISSING'    : '1',
 'TOPDOWN_CONTACT_TEACHER_BYPASS_UNLOCK'                     : '0',
 'TOPDOWN_CONTACT_TEACHER_CLOSE_RATE'                        : '0.006',
 'TOPDOWN_CONTACT_TEACHER_CLOSE_REQUIRES_DESCENT_READY'      : '0',
 'TOPDOWN_CONTACT_TEACHER_DESCENT_FULL_CLOSURE_FRACTION'     : '0.0',
 'TOPDOWN_CONTACT_TEACHER_DESCENT_MIN_CLOSURE_FRACTION'      : '0.0',
 'TOPDOWN_CONTACT_TEACHER_DESCENT_REQUIRES_CENTER'           : '1',
 'TOPDOWN_CONTACT_TEACHER_DESCENT_REQUIRES_WRIST_YAW_RELEASE': '0',
 'TOPDOWN_CONTACT_TEACHER_DESCENT_TIP_SERVO_XY_MAX_M'        : '0.03',
 'TOPDOWN_CONTACT_TEACHER_DESCENT_TIP_Z_TARGET'              : '0.0',
 'TOPDOWN_CONTACT_TEACHER_DESCENT_USES_CENTER_READY'         : '1',
 'TOPDOWN_CONTACT_TEACHER_DESCENT_USES_Z_NEED'               : '0',
 'TOPDOWN_CONTACT_TEACHER_DESCENT_Z'                         : '0.08',
 'TOPDOWN_CONTACT_TEACHER_DRIVE_AFTER_LIFT_LATCH'            : '1',
 'TOPDOWN_CONTACT_TEACHER_DRIVE_UNTIL_LIFT_LATCH'            : '1',
 'TOPDOWN_CONTACT_TEACHER_EXTRA_DESCENT_USES_CONTACT_MISSING': '0',
 'TOPDOWN_CONTACT_TEACHER_FINGER_ARM_HOLD_FALLBACK'          : '0',
 'TOPDOWN_CONTACT_TEACHER_FINGER_REQUIRES_CENTER'            : '0',
 'TOPDOWN_CONTACT_TEACHER_FINGER_UNLOCK_MIN'                 : '0.2',
 'TOPDOWN_CONTACT_TEACHER_HOLD_EXTRA_FRACTION'               : '0.1',
 'TOPDOWN_CONTACT_TEACHER_HOLD_MAX_FRACTION'                 : '0.78',
 'TOPDOWN_CONTACT_TEACHER_HOLD_ON_CONTACT'                   : '1',
 'TOPDOWN_CONTACT_TEACHER_INWARD_M'                          : '0.0',
 'TOPDOWN_CONTACT_TEACHER_INWARD_REQUIRES_CENTER'            : '1',
 'TOPDOWN_CONTACT_TEACHER_INWARD_VERTICAL_ONLY'              : '1',
 'TOPDOWN_CONTACT_TEACHER_MAX_FRACTION'                      : '0.78',
 'TOPDOWN_CONTACT_TEACHER_MIDDLE_SCALE'                      : '0.0',
 'TOPDOWN_CONTACT_TEACHER_MISSING_CONTACT_EXTRA_DESCENT'     : '0.005',
 'TOPDOWN_CONTACT_TEACHER_MISSING_CONTACT_EXTRA_INWARD'      : '0.0',
 'TOPDOWN_CONTACT_TEACHER_ONE_SIDED_CLOSE_BOOST'             : '1.0',
 'TOPDOWN_CONTACT_TEACHER_PRECENTER_SERVO'                   : '0',
 'TOPDOWN_CONTACT_TEACHER_PRELIFT_SQUEEZE_FRACTION'          : '0.68',
 'TOPDOWN_CONTACT_TEACHER_PRE_DESCENT_HOVER_HEIGHT_MAX'      : '0.035',
 'TOPDOWN_CONTACT_TEACHER_PRE_DESCENT_LIVE_DEBOUNCE_STEPS'   : '10',
 'TOPDOWN_CONTACT_TEACHER_SERVO_USES_LIVE_CONTACT'           : '0',
 'TOPDOWN_CONTACT_TEACHER_START_FRACTION'                    : '0.2',
 'TOPDOWN_CONTACT_TEACHER_TIP_SERVO_MAX_M'                   : '0.05',
 'TOPDOWN_CONTACT_TEACHER_VERTICAL_DROP_LOCK_XY'             : '0',
 'TOPDOWN_DYNAMIC_BLOCK'                                     : '1',
 'TOPDOWN_DYNAMIC_DISTRACTORS'                               : '0',
 'TOPDOWN_EPISODE_LENGTH_S'                                  : '10.0',
 'TOPDOWN_FINGERTIP_DYNAMIC_FRICTION'                        : '1.0',
 'TOPDOWN_FINGERTIP_STATIC_FRICTION'                         : '1.2',
 'TOPDOWN_FINGER_CLOSE_GATE_MODE'                            : 'xyz',
 'TOPDOWN_FINGER_XYZ_GATE_FULL_M'                            : '0.035',
 'TOPDOWN_FINGER_XYZ_GATE_LINEAR'                            : '1',
 'TOPDOWN_FINGER_XYZ_GATE_START_M'                           : '0.075',
 'TOPDOWN_GRIP_FINGER_MODEL'                                 : 'two_finger',
 'TOPDOWN_KEEP_DISTRACTORS_VISIBLE'                          : '1',
 'TOPDOWN_LIFT_FINGER_FREEZE_EXTRA_FRACTION'                 : '0.0',
 'TOPDOWN_LIFT_FINGER_FREEZE_MAX_FRACTION'                   : '0.78',
 'TOPDOWN_LIFT_FREEZE_FINGER_FRACTION_AT_LATCH'              : '1',
 'TOPDOWN_LIFT_GRIP_SETTLE_STEPS'                            : '0.0',
 'TOPDOWN_LIFT_LATCH_CONTACT_THRESHOLD'                      : '0.3',
 'TOPDOWN_LIFT_LATCH_HOLD_STEPS'                             : '3',
 'TOPDOWN_LIFT_LATCH_OPPOSED_FACE_MIN'                       : '-1.0',
 'TOPDOWN_LIFT_LATCH_REQUIRES_CENTER'                        : '0',
 'TOPDOWN_LIFT_LATCH_REQUIRES_CENTER_LIVE'                   : '0',
 'TOPDOWN_LIFT_LATCH_REQUIRES_DESCENT_Z_MIN'                 : '0.0',
 'TOPDOWN_LIFT_SQUEEZE_FRACTION'                             : '-1.0',
 'TOPDOWN_LIFT_SUCCESS_CONTACT_MIN'                          : '0.3',
 'TOPDOWN_LIFT_SUCCESS_HEIGHT'                               : '0.07',
 'TOPDOWN_LIFT_SUCCESS_HOLD_STEPS'                           : '15',
 'TOPDOWN_LIFT_SUCCESS_MODE'                                 : 'gated',
 'TOPDOWN_LIFT_SUCCESS_XY_DRIFT_MAX'                         : '0.5',
 'TOPDOWN_LIFT_TASK'                                         : '1',
 'TOPDOWN_LIFT_TERMINATE_DROP_FROM_MAX'                      : '0.025',
 'TOPDOWN_LIFT_TERMINATE_DROP_HOLD_STEPS'                    : '2',
 'TOPDOWN_LIFT_TERMINATE_DROP_MIN_PEAK'                      : '0.035',
 'TOPDOWN_MIRROR_MIDDLE_TO_INDEX'                            : '1',
 'TOPDOWN_OPPOSED_CONTACT_USE_MIDDLE_BACK'                   : '1',
 'TOPDOWN_PALM_LOCAL_GRIP_OFFSET_BLEND_REQUIRES_DESCENT'     : '1',
 'TOPDOWN_PALM_LOCAL_GRIP_OFFSET_LIVE_FULL_FRACTION'         : '0.8',
 'TOPDOWN_PALM_LOCAL_GRIP_OFFSET_LIVE_START_FRACTION'        : '0.5',
 'TOPDOWN_PALM_LOCAL_GRIP_OFFSET_MODE'                       : 'canonical_open',
 'TOPDOWN_POCKET_SWEEP'                                      : '1',
 'TOPDOWN_POCKET_SWEEP_ITERS'                                : '2',
 'TOPDOWN_POCKET_SWEEP_STAGE_MIN'                            : '1',
 'TOPDOWN_PREHOLD_ALIGN_ANGLE_GAIN'                          : '2.0',
 'TOPDOWN_PREHOLD_ALIGN_ANGLE_JOINTS'                        : 'all',
 'TOPDOWN_PREHOLD_ALIGN_ANGLE_MAX_DZ'                        : '0.05',
 'TOPDOWN_PREHOLD_ALIGN_ANGLE_MAX_JOINT_STEP'                : '0.05',
 'TOPDOWN_PREHOLD_ALIGN_ANGLE_SERVO'                         : '1',
 'TOPDOWN_PREHOLD_ALIGN_ANGLE_STAGE_MIN'                     : '0',
 'TOPDOWN_PREHOLD_ALIGN_CLEARANCE_ALIGN_ERR_MAX'             : '0.0',
 'TOPDOWN_PREHOLD_ALIGN_CLEARANCE_ANGLE_MAX_DEG'             : '0.0',
 'TOPDOWN_PREHOLD_ALIGN_CLEARANCE_M'                         : '0.035',
 'TOPDOWN_PREHOLD_CLEARANCE_UNTIL_CENTER'                    : '1',
 'TOPDOWN_PREHOLD_IK_POSITION_ONLY'                          : '1',
 'TOPDOWN_PREHOLD_IK_POSITION_ONLY_STAGE_MIN'                : '0',
 'TOPDOWN_PREHOLD_IK_TIP_SERVO_GAIN'                         : '0.75',
 'TOPDOWN_PREHOLD_IK_TIP_SERVO_MAX_M'                        : '0.05',
 'TOPDOWN_PREHOLD_IK_TIP_SERVO_STAGE_MIN'                    : '0',
 'TOPDOWN_PREHOLD_IK_TIP_SERVO_Z_REQUIRES_CENTER'            : '1',
 'TOPDOWN_PREHOLD_IK_WITH_CONTACT_TEACHER'                   : '1',
 'TOPDOWN_PREHOLD_PLANAR_ALIGN_GAIN'                         : '0.0',
 'TOPDOWN_PREHOLD_PLANAR_ALIGN_JOINTS'                       : 'all',
 'TOPDOWN_PREHOLD_PLANAR_ALIGN_MAX_JOINT_STEP'               : '0.0',
 'TOPDOWN_PREHOLD_PLANAR_ALIGN_MAX_XY'                       : '0.0',
 'TOPDOWN_PREHOLD_PLANAR_ALIGN_SERVO'                        : '0',
 'TOPDOWN_PREHOLD_PLANAR_ALIGN_STAGE_MIN'                    : '0',
 'TOPDOWN_PREHOLD_TIP_CLEARANCE_M'                           : '0.05',
 'TOPDOWN_PREROLL_FRACTION'                                  : '0.0',
 'TOPDOWN_PREROLL_MAX_STEPS'                                 : '250',
 'TOPDOWN_PREROLL_UNLOCK_PROGRESS'                           : '0.0',
 'TOPDOWN_SOURCE_POSE_MODE'                                  : 'red',
 'TOPDOWN_STAGE2_CENTER_BYPASSES_OPPOSED'                    : '1',
 'TOPDOWN_STAGE2_REQUIRES_FINGER_CENTER'                     : '1',
 'TOPDOWN_TARGET_PALM_BASIS'                                 : 'drop_priority',
 'TOPDOWN_TARGET_PALM_POSITION_MODE'                         : 'canonical_open',
 'TOPDOWN_TASK_SPACE_IK'                                     : '1',
 'TOPDOWN_TASK_SPACE_IK_CENTER_XY_WEIGHT'                    : '12.0',
 'TOPDOWN_TASK_SPACE_IK_CENTER_Z_WEIGHT'                     : '10.0',
 'TOPDOWN_TASK_SPACE_IK_DAMPING'                             : '0.045',
 'TOPDOWN_TASK_SPACE_IK_DIRECT_GRIP_CENTER'                  : '1',
 'TOPDOWN_TASK_SPACE_IK_DROP_WEIGHT'                         : '0.15',
 'TOPDOWN_TASK_SPACE_IK_LIFT_ORIENTATION_SCALE'              : '0.0',
 'TOPDOWN_TASK_SPACE_IK_LIFT_POSTURE_WEIGHT'                 : '0.0',
 'TOPDOWN_TASK_SPACE_IK_LIFT_SPAN_SCALE'                     : '0.0',
 'TOPDOWN_TASK_SPACE_IK_MAX_JOINT_STEP'                      : '0.05',
 'TOPDOWN_TASK_SPACE_IK_ORIENTATION_SIGN'                    : '1.0',
 'TOPDOWN_TASK_SPACE_IK_ORIENTATION_WEIGHT'                  : '0.15',
 'TOPDOWN_TASK_SPACE_IK_POSTURE_WEIGHT'                      : '0.08',
 'TOPDOWN_TASK_SPACE_IK_SPAN_XY_WEIGHT'                      : '2.0',
 'TOPDOWN_TASK_SPACE_IK_SPAN_Z_WEIGHT'                       : '18.0',
 'TOPDOWN_TIP_JACOBIAN_IK'                                   : '0',
 'TOPDOWN_TIP_JACOBIAN_IK_ACCEPT_WORSE'                      : '0',
 'TOPDOWN_TIP_JACOBIAN_IK_DAMPING'                           : '0.045',
 'TOPDOWN_TIP_JACOBIAN_IK_GAIN'                              : '1.05',
 'TOPDOWN_TIP_JACOBIAN_IK_JOINTS'                            : 'base',
 'TOPDOWN_TIP_JACOBIAN_IK_MAX_JOINT_STEP'                    : '0.06',
 'TOPDOWN_TIP_JACOBIAN_IK_MAX_WORSE_M'                       : '0.001',
 'TOPDOWN_TIP_JACOBIAN_IK_RESPECT_ARM_HOLD'                  : '0',
 'TOPDOWN_TIP_JACOBIAN_IK_STAGE_MIN'                         : '0',
 'TOPDOWN_TIP_JACOBIAN_IK_USE_MIDDLE'                        : '0',
 'TOPDOWN_TIP_JACOBIAN_IK_XY_WEIGHT'                         : '1.15',
 'TOPDOWN_TIP_JACOBIAN_IK_Z_REQUIRES_CENTER'                 : '1',
 'TOPDOWN_TIP_JACOBIAN_IK_Z_WEIGHT'                          : '2.0',
 'TOPDOWN_WRAP_TABLE'                                        : '1',
 'TOTAL_STEPS'                                               : '700000',
 'UPDATES_PER_STEP'                                          : '12',
 'WAIST_YAW_ACTION_SCALE'                                    : '1.0',
 'WRIST_YAW_RELEASE_AT_STAGE2': '0'}


def _remove_arg(command: list[str], flag: str, *, takes_value: bool = True) -> None:
    while flag in command:
        idx = command.index(flag)
        del command[idx]
        if takes_value and idx < len(command) and not command[idx].startswith("--"):
            del command[idx]


def _replace_arg(command: list[str], flag: str, value: Any) -> None:
    if flag in command:
        idx = command.index(flag)
        if idx + 1 < len(command) and not command[idx + 1].startswith("--"):
            command[idx + 1] = str(value)
        else:
            command.insert(idx + 1, str(value))
    else:
        command.extend([flag, str(value)])


def _set_flag(command: list[str], flag: str, enabled: bool) -> None:
    if enabled:
        if flag not in command:
            command.append(flag)
    else:
        _remove_arg(command, flag, takes_value=False)


def _force_v35_entrypoint(command: list[str]) -> None:
    """Ensure flattened v35 plans launch the native training module."""

    if not V35_MODULE:
        return
    if "-m" in command:
        idx = command.index("-m")
        if idx + 1 < len(command):
            command[idx + 1] = V35_MODULE
        else:
            command.append(V35_MODULE)
        return
    for idx, item in enumerate(list(command)):
        if item.endswith(".py") or item.startswith("scripts/"):
            command[idx:idx + 1] = ["-m", V35_MODULE]
            return
    command.extend(["-m", V35_MODULE])


def apply_v35_base(command: list[str], env: dict[str, str]) -> None:
    """Apply the full flattened v35 contract to a mutable command/env plan."""

    _force_v35_entrypoint(command)
    env.update(V35_BASE_ENV)
    for flag, value in V35_BASE_ARGS.items():
        if isinstance(value, bool):
            _set_flag(command, flag, value)
        else:
            _replace_arg(command, flag, value)
