"""

Phase 0: snap into centered strict contact before learning lift


build_phase:  Builds the phase specification for the pre-lift strict contact stage,
                where the agent must learn to achieve and hold a centered strict contact pose without lifting before progressing.
"""

from __future__ import annotations

from training.curriculum.envs import default_phase_env, strict_contact_no_lift_env
from training.curriculum.spec import PhaseSpec


def build_phase(
    *,
    steps                              : int        = 500_000,
    start_steps                        : int        = 50_000,
    bc_only_steps                      : int        = 200_000,
    rl_phase_start_steps               : int        = -1,
    assist_mix                         : float      = 1.0,
    assist_floor                       : float      = 0.98,
    assist_decay_steps                 : int | None = None,
    success_height                     : float      = 0.0,
    success_hold_steps                 : int        = 30,
    success_contact_min                : float      = 0.30,
    success_xy_drift_max               : float      = 0.10,
    success_block_tilt_max_deg         : float      = 20.0,
    success_center_tip_xy_max          : float      = 0.03,
    success_center_tip_z_max           : float      = 0.03,
    success_center_align_angle_max_deg : float      = 8.0,
    min_success_rate                   : float      = 0.80,
    min_median_lift                    : float      = 0.0,
    max_median_disp                    : float      = 0.050,
    score_drop_limit                   : float      = 6.0,
    regression_patience_steps          : int        = 1_000_000,
    block_drift_threshold              : float      = 999.0,
    contact_block_disp_max             : float      = 999.0,
    lift_terminate_drop_from_max       : float      = 0.0,
    lift_terminate_drop_min_peak       : float      = 999.0,
    lift_terminate_drop_hold_steps     : int        = 999999,
    contact_target_distance            : float      = -6.0,
    contact_vertical_gap               : float      = -6.0,
    contact_thumb_contact              : float      = 1.5,
    contact_index_contact              : float      = 1.5,
    contact_opposed_contact            : float      = 24.0,
    contact_bilateral_contact          : float      = 8.0,
    contact_bilateral_imbalance        : float      = -2.0,
    contact_one_sided                  : float      = -2.0,
    contact_one_sided_flip             : float      = -1.0,
    contact_deep_shell                 : float      = 8.0,
    contact_centered_contact           : float      = 12.0,
    contact_smooth_success_pose        : float      = 10.0,
    contact_smooth_success_with_contact: float      = 16.0,
    light_contact_success_bonus        : float      = 80.0,
    stage2_floor                       : float      = 0.75,
    lift_height_progress               : float      = 0.0,
    contact_lift_progress              : float      = 0.0,
    lift_with_grip                     : float      = 0.0,
    centered_lift_progress             : float      = 0.0,
    centered_upright_lift_bonus        : float      = 0.0,
    block_off_table_bonus              : float      = 0.0,
    block_xy_velocity_penalty          : float      = -2.0,
    block_angular_velocity_penalty     : float      = -2.0,
    lift_xy_drift_penalty              : float      = 0.0,
    block_tilt_lift_penalty            : float      = 0.0,
    uncentered_lift_penalty            : float      = 0.0,
    block_drop_penalty                 : float      = 0.0,
) -> PhaseSpec:
    env = {
        **default_phase_env(),
        "TOPDOWN_LIFT_SUCCESS_MODE"                    : "gated",
        "TOPDOWN_LIFT_SUCCESS_REQUIRES_CONTACT"        : "1",
        "TOPDOWN_LIFT_SUCCESS_CONTACT_MODE"            : "light",
        "TOPDOWN_LIFT_SUCCESS_CONTACT_MIN"             : str(success_contact_min),
        "CURRICULUM_CONTACT_STRENGTH_MIN"              : str(success_contact_min),
        "TOPDOWN_LIFT_SUCCESS_HEIGHT"                  : str(success_height),
        "TOPDOWN_LIFT_SUCCESS_HOLD_STEPS"              : str(success_hold_steps),
        "TOPDOWN_LIFT_SUCCESS_XY_DRIFT_MAX"            : str(success_xy_drift_max),
        "TOPDOWN_LIFT_SUCCESS_BLOCK_TILT_MAX_DEG"      : str(success_block_tilt_max_deg),
        "CURRICULUM_SUCCESS_REQUIRE_CENTERED_CONTACT"  : "1",
        "CURRICULUM_SUCCESS_CENTER_TIP_XY_MAX"         : str(success_center_tip_xy_max),
        "CURRICULUM_SUCCESS_CENTER_TIP_Z_MAX"          : str(success_center_tip_z_max),
        "CURRICULUM_SUCCESS_CENTER_ALIGN_ANGLE_MAX_DEG": str(success_center_align_angle_max_deg),
        "CURRICULUM_BLOCK_DRIFT_THRESHOLD"             : str(block_drift_threshold),
        "CURRICULUM_CONTACT_BLOCK_DISP_MAX"            : str(contact_block_disp_max),
        "TOPDOWN_LIFT_TERMINATE_DROP_FROM_MAX"         : str(lift_terminate_drop_from_max),
        "TOPDOWN_LIFT_TERMINATE_DROP_MIN_PEAK"         : str(lift_terminate_drop_min_peak),
        "TOPDOWN_LIFT_TERMINATE_DROP_HOLD_STEPS"       : str(lift_terminate_drop_hold_steps),
        **strict_contact_no_lift_env(
            contact_target_distance=contact_target_distance,
            contact_vertical_gap=contact_vertical_gap,
            contact_thumb_contact=contact_thumb_contact,
            contact_index_contact=contact_index_contact,
            contact_opposed_contact=contact_opposed_contact,
            contact_bilateral_contact=contact_bilateral_contact,
            contact_bilateral_imbalance=contact_bilateral_imbalance,
            contact_one_sided=contact_one_sided,
            contact_one_sided_flip=contact_one_sided_flip,
            contact_deep_shell=contact_deep_shell,
            contact_centered_contact=contact_centered_contact,
            contact_smooth_success_pose=contact_smooth_success_pose,
            contact_smooth_success_with_contact=contact_smooth_success_with_contact,
            light_contact_success_bonus=light_contact_success_bonus,
            stage2_floor=stage2_floor,
            lift_height_progress=lift_height_progress,
            contact_lift_progress=contact_lift_progress,
            lift_with_grip=lift_with_grip,
            centered_lift_progress=centered_lift_progress,
            centered_upright_lift_bonus=centered_upright_lift_bonus,
            block_off_table_bonus=block_off_table_bonus,
            block_xy_velocity_penalty=block_xy_velocity_penalty,
            block_angular_velocity_penalty=block_angular_velocity_penalty,
            lift_xy_drift_penalty=lift_xy_drift_penalty,
            block_tilt_lift_penalty=block_tilt_lift_penalty,
            uncentered_lift_penalty=uncentered_lift_penalty,
            block_drop_penalty=block_drop_penalty,
        ),
    }
    return PhaseSpec(
        name="p00_strict_contact_nolift",
        description=(
            "Pre-lift transfer stage: held centered strict/light contact succeeds; "
            "lift is neutral and the phase advances only when contact is held without large drift."
        ),
        steps=steps,
        start_steps=start_steps,
        bc_only_steps=bc_only_steps,
        rl_phase_start_steps=rl_phase_start_steps,
        assist_mix=assist_mix,
        assist_floor=assist_floor,
        assist_decay_steps=assist_decay_steps if assist_decay_steps is not None else steps,
        success_height=success_height,
        success_hold_steps=success_hold_steps,
        min_success_rate=min_success_rate,
        min_median_lift=min_median_lift,
        max_median_disp=max_median_disp,
        score_drop_limit=score_drop_limit,
        regression_patience_steps=regression_patience_steps,
        env=env,
        args={},
    )


__all__ = ["build_phase"]
