# Copyright (c) 2025, Unitree Robotics Co., Ltd. All Rights Reserved.
# License: Apache License, Version 2.0

"""MDP terms for the topdown reach-align-contact curriculum."""

from isaaclab.envs.mdp import *

from . import state_machine  # noqa: F401
from . import observations  # noqa: F401
from . import rewards  # noqa: F401
from . import terminations  # noqa: F401
from . import trainer_helpers  # noqa: F401
from .state_machine import (  # noqa: F401
    ensure_curriculum_stage_updated,
    palm_distance,
    palm_height_error,
    palm_drop_axis_error_rad,
    palm_orient_error_rad,
    palm_yaw_axis_error_rad,
    palm_spread_axis_error_rad,
    open_hand_alignment_error,
    fingertip_line_angle_rad,
    opposite_face_gate,
    centered_contact_errors,
    centered_contact_shell_now,
    any_hand_contact_strength,
    thumb_contact_strength,
    index_contact_strength,
    palm_contact_strength,
    middle_contact_strength,
    opposed_contact_strength,
    block_displacement,
    block_xy_displacement,
    block_lift_height,
    block_linear_velocity,
    block_z_velocity,
    block_xy_velocity_norm,
    block_angular_velocity_norm,
    block_tilt_angle_rad,
    light_contact_success_now,
    light_contact_success_held,
    lift_success_now,
    lift_success_held,
    stage_one_hot,
    finger_unlock_progress,
    contact_pose_shell_now,
)
from tasks.common_observations.dex3_state import get_robot_dex3_joint_states  # noqa: F401
from tasks.common_observations.g1_29dof_state import get_robot_boy_joint_states  # noqa: F401

from .observations import (  # noqa: F401
    get_palm_pos_world,
    get_palm_quat_world,
    get_block_pos_world,
    get_block_quat_world,
    get_grip_target_pos_world,
    get_block_minus_palm,
    get_thumb_tip_pos_world,
    get_index_tip_pos_world,
    get_middle_tip_pos_world,
    get_thumb_minus_block,
    get_index_minus_block,
    get_middle_minus_block,
    get_palm_pose_scalars,
    get_axis_orientation_scalars,
    get_alignment_scalars,
    get_contact_strengths,
    get_lift_scalars,
    get_tip_target_error_scalars,
    get_physical_block_scalars,
    get_source_block_one_hot,
    episode_step_fraction,
    get_controller_state_scalars,
    get_teacher_contact_state_scalars,
    get_teacher_ik_state_scalars,
    get_arm_hold_action_scalars,
)
from .rewards import (  # noqa: F401
    reach_palm_distance,
    reach_palm_height,
    reach_palm_orientation,
    reach_palm_yaw_axis,
    reach_palm_spread_axis,
    reach_alignment_error_quadratic,
    reach_fingertip_line_angle_quadratic,
    reach_shell_bonus,
    align_palm_distance_maintenance,
    align_palm_height_maintenance,
    align_palm_orientation_maintenance,
    align_palm_yaw_axis_maintenance,
    align_alignment_error,
    align_fingertip_line_angle,
    align_alignment_error_quadratic,
    align_fingertip_line_angle_quadratic,
    align_opposite_face,
    align_shell_bonus,
    contact_palm_distance_maintenance,
    contact_palm_height_maintenance,
    contact_palm_orientation_maintenance,
    contact_palm_yaw_axis_maintenance,
    contact_alignment_error_maintenance,
    contact_alignment_error_quadratic,
    alignment_degradation_penalty,
    contact_fingertip_line_angle_maintenance,
    contact_opposite_face_maintenance,
    contact_target_distance,
    contact_vertical_gap,
    contact_thumb_contact_bonus,
    contact_index_contact_bonus,
    contact_opposed_bonus,
    contact_preunlock_pocket_quality,
    contact_preunlock_no_contact_penalty,
    contact_bilateral_contact_bonus,
    contact_bilateral_imbalance_penalty,
    contact_one_sided_flip_penalty,
    contact_lift_progress,
    lift_height_progress,
    lift_with_grip,
    centered_lift_progress,
    vertical_lift_velocity_bonus,
    block_xy_velocity_penalty,
    block_angular_velocity_penalty,
    block_upright_lift_bonus,
    centered_upright_lift_bonus,
    lift_xy_drift_penalty,
    block_tilt_lift_penalty,
    uncentered_lift_penalty,
    block_off_table_bonus,
    sustained_lift_grip_bonus,
    block_drop_penalty,
    contact_deep_shell_bonus,
    stage2_floor_reward,
    contact_one_sided_penalty,
    contact_overforce_penalty,
    contact_pose_ready_no_contact_penalty,
    contact_smooth_pose_no_contact_penalty,
    contact_finger_center_x_error_quadratic,
    contact_finger_center_y_error_quadratic,
    contact_centered_contact_continuous,
    contact_success_now_continuous,
    contact_smooth_success_continuous,
    contact_smooth_success_pose_continuous,
    contact_smooth_success_with_contact_continuous,
    light_contact_success_bonus,
    step_cost,
    action_rate_l2,
)
from .terminations import (  # noqa: F401
    light_contact_success,
    block_drifted,
    alignment_timeout_bad,
)
